#!/bin/bash

# scripts/generate_todo.sh
OUTPUT_FILE="todo_list.md"
KEYWORDS="TODO|FIXME|PERF|OPTIMIZE|HACK"

# 1. Check if there are any changes to TODO keywords in staged files
# If this is not a pre-commit run (no staged changes), we might want to run anyway
if [ -n "$(git rev-parse --is-inside-work-tree 2>/dev/null)" ]; then
    # git diff -G scans the content for the pattern
    if git diff --cached --quiet -G"$KEYWORDS" && [ -f "$OUTPUT_FILE" ]; then
        # No keyword changes in staged files, skip for performance
        exit 0
    fi
fi

# 2. Generate new content in a temporary buffer
TEMP_CONTENT=$(mktemp)

cat << EOF > "$TEMP_CONTENT"
# Project Task List

This file is automatically generated.
Last updated: $(date)

EOF

# Scan all tracked files (respecting .gitignore) excluding docs
git ls-files --cached --others --exclude-standard | \
    grep -vE "CONTRIBUTING.md|LICENSE|README.md|README_en.md|todo_list.md" | \
    xargs grep -nE "$KEYWORDS" /dev/null 2>/dev/null | while read -r line; do

    file=$(echo "$line" | cut -d: -f1)
    lnum=$(echo "$line" | cut -d: -f2)
    text=$(echo "$line" | cut -d: -f3-)

    # Clean up
    text=$(echo "$text" | sed 's/^[ \t\/*#]*//;s/[ \t\/*#]*$//')
    echo "- [ ] **$file:$lnum** - $text" >> "$TEMP_CONTENT"
done

# 3. Smart Update: Compare content (ignoring the 'Last updated' line)
if [ -f "$OUTPUT_FILE" ]; then
    # Extract just the task lines (starting with - [ ]) to compare
    NEW_TASKS=$(grep "^- \[ \]" "$TEMP_CONTENT")
    OLD_TASKS=$(grep "^- \[ \]" "$OUTPUT_FILE")

    if [ "$NEW_TASKS" == "$OLD_TASKS" ]; then
        # No actual task changes, don't touch the file
        rm "$TEMP_CONTENT"
        exit 0
    fi
fi

# 4. Content is different, update the file
mv "$TEMP_CONTENT" "$OUTPUT_FILE"
echo "Task list updated in $OUTPUT_FILE."
