#!/bin/bash

# Output file
OUTPUT_FILE="todo_list.md"

# Keywords to search for
KEYWORDS="TODO|FIXME|PERF|OPTIMIZE|HACK"

echo "Scanning for tasks ($KEYWORDS) respecting .gitignore..."

# Create/Empty the output file
cat << EOF > "$OUTPUT_FILE"
# Project Task List

This file is automatically generated by \`scripts/generate_todo.sh\`.
Last updated: $(date)

EOF

# Use git ls-files to respect .gitignore
# Then filter out common documentation files to avoid false positives
git ls-files --cached --others --exclude-standard | \
    grep -vE "CONTRIBUTING.md|LICENSE|README.md|README_en.md" | \
    xargs grep -nE "$KEYWORDS" /dev/null 2>/dev/null | while read -r line; do
    
    # Parse grep output (format: file:line:text)
    file=$(echo "$line" | cut -d: -f1)
    lnum=$(echo "$line" | cut -d: -f2)
    text=$(echo "$line" | cut -d: -f3-)
    
    # Skip the todo_list.md itself and the generation script to avoid self-referencing
    if [[ "$file" == "$OUTPUT_FILE" || "$file" == "scripts/generate_todo.sh" ]]; then
        continue
    fi

    # Clean up whitespace and comment markers (//, #, /*, *) from text
    text=$(echo "$text" | sed 's/^[ \t\/*#]*//;s/[ \t\/*#]*$//')
    
    # Append to markdown file
    echo "- [ ] **$file:$lnum** - $text" >> "$OUTPUT_FILE"
done

echo "Done! Task list generated in $OUTPUT_FILE."
